logs_folder_path: "path/to/logs/folder"
exclude_path:
  - "docs/*"
  - "internal/tests/*"
  - "*.md"
ignore_rule_id:
  - "github-pat"
ignore_result_id:
  - "6981a34c1d94db7b5465fbc8b8f4fb97c2c97426"
allow_skip: false