name: Tag and Release on Push to Main

on:
  push:
    branches:
      - main

jobs:
  download_2ms:
    runs-on: ubuntu-latest

    steps:
      - name: delete 2ms binary if exists
        run: |
          rm -rf pkg/2ms
      - name: Download 2ms binary
        run: |
          MICRO_ENGINE_VERSION=$(cat 2ms_version.txt)
          MICRO_ENGINE_URL="https://github.com/Checkmarx/2ms/releases/download/v${MICRO_ENGINE_VERSION}/linux-amd64.zip"
          wget ${MICRO_ENGINE_URL} -O 2ms.zip && unzip 2ms.zip -d pkg/2ms
      - name: commit 2ms binary
        run: |
          git add bin/*
          git commit -m "Update 2ms binary"
          git push
  create_tag_and_release:
    runs-on: ubuntu-latest
    needs: download_2ms
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get the current version
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "::set-output name=VERSION::$VERSION"

      - name: Create new tag
        id: create_tag
        run: |
          NEW_TAG=$(echo ${{ steps.get_version.outputs.VERSION }} | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo "New tag: $NEW_TAG"
          git tag $NEW_TAG
          git push origin $NEW_TAG