name: Secret Module CI

on:
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.0.0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Debug Environment Variables
        run: |
          echo "CX_BASE_URI is set"
          echo "CX_BASE_AUTH_URI is set"
          echo "CX_APIKEY is set"
          echo "CX_TENANT is set"
        shell: bash
        env:
          CX_BASE_URI: ${{ secrets.CX_BASE_URI }}
          CX_BASE_AUTH_URI: ${{ secrets.CX_BASE_AUTH_URI }}
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
          CX_TENANT: ${{ secrets.CX_TENANT }}

      - name: Clone AST CLI Repository from pre-commit-hook branch
        run: |
          git clone --branch pre-commit-hook https://github.com/Checkmarx/ast-cli.git
          cd ast-cli
          go build -o cx ./cmd/cx.go
          sudo mv cx /usr/local/bin/

      - name: Configure AST CLI
        env:
          CX_BASE_URI: ${{ secrets.CX_BASE_URI }}
          CX_BASE_AUTH_URI: ${{ secrets.CX_BASE_AUTH_URI }}
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
          CX_TENANT: ${{ secrets.CX_TENANT }}
        run: |
          cx configure set --base-uri "$CX_BASE_URI"
          cx configure set --base-auth-uri "$CX_BASE_AUTH_URI"
          cx configure set --tenant "$CX_TENANT"
          cx auth --apikey "$CX_APIKEY"

      - name: Verify AST CLI Installation
        run: cx version
