name: Commit Convention

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commit-convention:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install commitlint
        run: npm install @commitlint/{config-conventional,cli} --save-dev

      - name: Create commitlint config
        run: echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js

      - name: Lint commits
        run: npx commitlint --from=HEAD~1 --to=HEAD