name: security checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '5 6 * * *'  # Runs every day at 06:05 UTC

jobs:
  trivy-scan:
    name: Trivy scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@v0.30.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          output: results.txt
          severity: CRITICAL,HIGH,MEDIUM,LOW
          skip-dirs: .github
          exit-code: 1
        env:
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true
      - name: Inspect action report
        if: always()
        run: cat results.txt
  grype-scan:
    name: Grype scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run Grype vulnerability scanner in repo mode
        id: grype-fs-scan
        uses: anchore/scan-action@2c901ab7378897c01b8efaa2d0c9bf519cc64b9e # v6.2.0
        with:
          path: "."
          only-fixed: true
          output-format: table
          severity-cutoff: low
          fail-build: true
  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #v5.0.0
        with:
          go-version-file: go.mod
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GOPRIVATE: github.com/Checkmarx/*,github.com/checkmarx/*

      - name: Install dependencies
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Scan
        run: govulncheck ./...