name: Secret module Tests

on:
  workflow_dispatch:  # Allow manual triggering
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 7 * * *' # Every day at 07:00

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 #v4.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Get secret-detection commit SHA
        id: sd_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Go version
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 #v4
        with:
          go-version-file: go.mod

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pre-commit framework
        run: |
          echo "Installing pre-commit framework in a virtual environment..."
          python3 -m venv /opt/venv
          source /opt/venv/bin/activate
          pip install --upgrade pip
          pip install pre-commit
          echo "/opt/venv/bin" >> $GITHUB_PATH
          echo "pre-commit installed successfully."

      - run: go version

      - name: Download AST CLI
        run: |
          git clone --branch feature/pre-receive-demo https://github.com/Checkmarx/ast-cli.git
          cd ast-cli
          go get github.com/Checkmarx/secret-detection@${{ steps.sd_sha.outputs.sha }}
          go mod tidy
          go build -o cx ./cmd
          sudo mv cx /usr/local/bin/

      - name: Configure AST CLI
        shell: bash
        env:
          CX_BASE_URI: ${{ secrets.CX_BASE_URI }}
          CX_BASE_AUTH_URI: ${{ secrets.CX_BASE_AUTH_URI }}
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
          CX_TENANT: ${{ secrets.CX_TENANT }}
          CX_CLIENT_ID: ${{ secrets.CX_CLIENT_ID }}
          CX_CLIENT_SECRET: ${{ secrets.CX_CLIENT_SECRET }}
        run: |
          echo "Configuring AST CLI..."
          cx configure set --prop-name cx_base_uri --prop-value "$CX_BASE_URI"
          cx configure set --prop-name cx_base_auth_uri --prop-value "$CX_BASE_AUTH_URI"
          cx configure set --prop-name cx_tenant --prop-value "$CX_TENANT"
          cx configure set --prop-name cx_client_id --prop-value "$CX_CLIENT_ID"
          cx configure set --prop-name cx_client_secret --prop-value "$CX_CLIENT_SECRET"
          echo "Authenticating AST CLI..."
          cx auth validate
          echo "AST CLI configured and authenticated."
      - run: cx version

      - name: Run unit and integration tests
        run: go test -v ./...
  lint:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.6

      - name: Install golangci-lint
        run: |
          # install a specific version or latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run linter
        run: golangci-lint run
  grype-scan:
    name: Grype scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run Grype scan
        id: grype-fs-scan
        uses: anchore/scan-action@2c901ab7378897c01b8efaa2d0c9bf519cc64b9e # v6.2.0
        with:
          path: "."
          only-fixed: true
          output-format: table
          severity-cutoff: low
          fail-build: true
  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #v5.0.0
        with:
          go-version-file: go.mod
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GOPRIVATE: github.com/Checkmarx/*,github.com/checkmarx/*

      - name: Install dependencies
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Scan
        run: govulncheck ./...