name: Trivy-scan
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '5 6 * * *'  # Runs every day at 06:05 UTC

jobs:
  trivy-scan:
    name: Trivy scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          output: results.txt
          severity: CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN
          exit-code: 1
        env:
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true
      - name: Inspect action report
        if: always()
        run: cat results.txt